CMD:cj(playerid, params[])
{
    SetPlayerPos(playerid, 2490.30, -1666.67, 13.34);
    return 1;
}

CMD:idlewood(playerid, params[])
{
    SetPlayerPos(playerid, 1953.74, -1759.88, 13.54);
    return 1;
}

CMD:ls(playerid, params[])
{
    SetPlayerPos(playerid, 1538.16, -1675.73, 13.54);
    return 1;
}

CMD:lv(playerid, params[])
{
    SetPlayerPos(playerid, 2169.56, 1676.70, 10.82);
    return 1;
}

CMD:area51(playerid, params[])
{

    SetPlayerPos(playerid, 96.47, 1949.38, 17.64);
    return 1;
}

alias:angelpine("ap","angelp")
CMD:angelpine(playerid, params[])
{
    SetPlayerPos(playerid, -2044.01, -2381.33, 30.63);
    return 1;
}

CMD:sf(playerid, params[])
{
    SetPlayerPos(playerid, -1600.00, 265.00, 6.00);
    return 1;
}

